// <auto-generated />
using System;
using BikeRentalPoint.Infrastructure.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BikeRentalPoint.Infrastructure.EfCore.Migrations
{
    [DbContext(typeof(BikeRentalPointDbContext))]
    [Migration("20251124192718_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BikeRentalPoint.Domain.Models.Bike", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("color");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("char(36)")
                        .HasColumnName("model_id");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("serial_number");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("bike", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d76ea574-e417-4567-a4b3-fd59c314d391"),
                            Color = "Red",
                            ModelId = new Guid("aadbd9ee-2517-40f8-9db3-a1161a6c16a5"),
                            SerialNumber = "101"
                        },
                        new
                        {
                            Id = new Guid("745b41c8-ca80-427c-9e86-152b5a1ba5f4"),
                            Color = "Blue",
                            ModelId = new Guid("1a96f120-7e4e-4e36-a536-07aa6df6112c"),
                            SerialNumber = "102"
                        },
                        new
                        {
                            Id = new Guid("80d70b89-4692-4eda-9492-cf898aac545d"),
                            Color = "Black",
                            ModelId = new Guid("e0350b2c-8f99-49d5-b4eb-4f1165b87abc"),
                            SerialNumber = "103"
                        },
                        new
                        {
                            Id = new Guid("9ca5637c-9c10-419e-9c35-db2d523f5b08"),
                            Color = "Green",
                            ModelId = new Guid("ec4c0299-7e52-44cb-9fd9-9fd8f2990232"),
                            SerialNumber = "104"
                        },
                        new
                        {
                            Id = new Guid("279902b6-a996-4fe1-8de8-0f36cfcff3eb"),
                            Color = "White",
                            ModelId = new Guid("ec369c47-c55e-4825-8a3d-438949233514"),
                            SerialNumber = "105"
                        },
                        new
                        {
                            Id = new Guid("2ff0d2de-a373-41ae-8018-f08f2590ec88"),
                            Color = "Yellow",
                            ModelId = new Guid("c87a3abb-ff4d-45ed-a9d0-88055b9673cf"),
                            SerialNumber = "106"
                        },
                        new
                        {
                            Id = new Guid("3c43bc36-34e8-4fe3-ba3d-9b52777c6976"),
                            Color = "Silver",
                            ModelId = new Guid("81baa0bc-eef3-4797-ba5a-d8e4d862a37a"),
                            SerialNumber = "107"
                        },
                        new
                        {
                            Id = new Guid("e2330abb-386b-45fe-8c3b-52ec852dee1f"),
                            Color = "Gray",
                            ModelId = new Guid("fb93836e-474f-48f7-b8fd-2eb25b21f30d"),
                            SerialNumber = "108"
                        },
                        new
                        {
                            Id = new Guid("61865875-b804-4baa-8b2a-3260e62b84f3"),
                            Color = "Orange",
                            ModelId = new Guid("a72e8761-ee46-4c3d-a7e0-0d6b17523f16"),
                            SerialNumber = "109"
                        },
                        new
                        {
                            Id = new Guid("36358c4c-8620-4fb5-9502-e1ea23d0d3e1"),
                            Color = "Purple",
                            ModelId = new Guid("49e4174e-b015-4340-a0fc-dfef5947961a"),
                            SerialNumber = "110"
                        });
                });

            modelBuilder.Entity("BikeRentalPoint.Domain.Models.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("BikeType")
                        .HasColumnType("int")
                        .HasColumnName("bike_type");

                    b.Property<double?>("BikeWeight")
                        .HasColumnType("double")
                        .HasColumnName("bike_weight");

                    b.Property<int>("BrakeType")
                        .HasColumnType("int")
                        .HasColumnName("brake_type");

                    b.Property<double?>("MaxPassengerWeight")
                        .HasColumnType("double")
                        .HasColumnName("max_passenger_weight");

                    b.Property<int?>("ModelYear")
                        .HasColumnType("int")
                        .HasColumnName("model_year");

                    b.Property<decimal>("PricePerHour")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price_per_hour");

                    b.Property<double?>("WheelSize")
                        .HasColumnType("double")
                        .HasColumnName("wheel_size");

                    b.HasKey("Id");

                    b.ToTable("model", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aadbd9ee-2517-40f8-9db3-a1161a6c16a5"),
                            BikeType = 0,
                            BikeWeight = 9.0,
                            BrakeType = 1,
                            MaxPassengerWeight = 100.0,
                            ModelYear = 2022,
                            PricePerHour = 12m,
                            WheelSize = 28.0
                        },
                        new
                        {
                            Id = new Guid("1a96f120-7e4e-4e36-a536-07aa6df6112c"),
                            BikeType = 1,
                            BikeWeight = 11.0,
                            BrakeType = 0,
                            MaxPassengerWeight = 110.0,
                            ModelYear = 2021,
                            PricePerHour = 10m,
                            WheelSize = 26.0
                        },
                        new
                        {
                            Id = new Guid("e0350b2c-8f99-49d5-b4eb-4f1165b87abc"),
                            BikeType = 1,
                            BikeWeight = 13.0,
                            BrakeType = 1,
                            MaxPassengerWeight = 120.0,
                            ModelYear = 2023,
                            PricePerHour = 15m,
                            WheelSize = 29.0
                        },
                        new
                        {
                            Id = new Guid("ec4c0299-7e52-44cb-9fd9-9fd8f2990232"),
                            BikeType = 2,
                            BikeWeight = 10.0,
                            BrakeType = 0,
                            MaxPassengerWeight = 90.0,
                            ModelYear = 2020,
                            PricePerHour = 9m,
                            WheelSize = 27.5
                        },
                        new
                        {
                            Id = new Guid("ec369c47-c55e-4825-8a3d-438949233514"),
                            BikeType = 0,
                            BikeWeight = 12.0,
                            BrakeType = 2,
                            MaxPassengerWeight = 100.0,
                            ModelYear = 2024,
                            PricePerHour = 14m,
                            WheelSize = 28.0
                        },
                        new
                        {
                            Id = new Guid("c87a3abb-ff4d-45ed-a9d0-88055b9673cf"),
                            BikeType = 4,
                            BikeWeight = 8.0,
                            BrakeType = 3,
                            MaxPassengerWeight = 80.0,
                            ModelYear = 2019,
                            PricePerHour = 8m,
                            WheelSize = 24.0
                        },
                        new
                        {
                            Id = new Guid("81baa0bc-eef3-4797-ba5a-d8e4d862a37a"),
                            BikeType = 3,
                            BikeWeight = 14.0,
                            BrakeType = 1,
                            MaxPassengerWeight = 100.0,
                            ModelYear = 2024,
                            PricePerHour = 16m,
                            WheelSize = 26.0
                        },
                        new
                        {
                            Id = new Guid("fb93836e-474f-48f7-b8fd-2eb25b21f30d"),
                            BikeType = 1,
                            BikeWeight = 15.0,
                            BrakeType = 5,
                            MaxPassengerWeight = 130.0,
                            ModelYear = 2023,
                            PricePerHour = 13m,
                            WheelSize = 29.0
                        },
                        new
                        {
                            Id = new Guid("a72e8761-ee46-4c3d-a7e0-0d6b17523f16"),
                            BikeType = 2,
                            BikeWeight = 11.0,
                            BrakeType = 0,
                            MaxPassengerWeight = 95.0,
                            ModelYear = 2021,
                            PricePerHour = 11m,
                            WheelSize = 27.0
                        },
                        new
                        {
                            Id = new Guid("49e4174e-b015-4340-a0fc-dfef5947961a"),
                            BikeType = 0,
                            BikeWeight = 12.0,
                            BrakeType = 1,
                            MaxPassengerWeight = 120.0,
                            ModelYear = 2025,
                            PricePerHour = 17m,
                            WheelSize = 28.0
                        });
                });

            modelBuilder.Entity("BikeRentalPoint.Domain.Models.Rent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("BikeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("bike_id");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time(6)")
                        .HasColumnName("duration");

                    b.Property<Guid>("RenterId")
                        .HasColumnType("char(36)")
                        .HasColumnName("renter_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("BikeId");

                    b.HasIndex("RenterId");

                    b.ToTable("rent", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d56a4c5a-3c15-4886-8fd4-73fec0a831b3"),
                            BikeId = new Guid("d76ea574-e417-4567-a4b3-fd59c314d391"),
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            RenterId = new Guid("9cec14bf-3470-4394-9899-fdf3519f699f"),
                            StartTime = new DateTime(2025, 11, 22, 21, 27, 17, 176, DateTimeKind.Local).AddTicks(6419)
                        },
                        new
                        {
                            Id = new Guid("fa62f9da-bbc4-40dc-b24f-97d190aa20bc"),
                            BikeId = new Guid("745b41c8-ca80-427c-9e86-152b5a1ba5f4"),
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            RenterId = new Guid("590c9949-a9d3-4084-81b4-d2b5c59cc0e7"),
                            StartTime = new DateTime(2025, 11, 23, 7, 27, 17, 176, DateTimeKind.Local).AddTicks(7003)
                        },
                        new
                        {
                            Id = new Guid("8825d79f-eb62-4d72-bef2-366e86bd0ed7"),
                            BikeId = new Guid("80d70b89-4692-4eda-9492-cf898aac545d"),
                            Duration = new TimeSpan(0, 4, 0, 0, 0),
                            RenterId = new Guid("9bf4355d-d000-4822-9bd1-dea296610a3a"),
                            StartTime = new DateTime(2025, 11, 23, 17, 27, 17, 176, DateTimeKind.Local).AddTicks(7007)
                        },
                        new
                        {
                            Id = new Guid("86dd46d2-d590-453c-ab9a-47a498917b81"),
                            BikeId = new Guid("9ca5637c-9c10-419e-9c35-db2d523f5b08"),
                            Duration = new TimeSpan(0, 1, 30, 0, 0),
                            RenterId = new Guid("d8abaf64-e960-486d-a064-7134dc4c0522"),
                            StartTime = new DateTime(2025, 11, 24, 3, 27, 17, 176, DateTimeKind.Local).AddTicks(7020)
                        },
                        new
                        {
                            Id = new Guid("3693a260-f88c-4fea-8535-250979eda36f"),
                            BikeId = new Guid("279902b6-a996-4fe1-8de8-0f36cfcff3eb"),
                            Duration = new TimeSpan(0, 2, 30, 0, 0),
                            RenterId = new Guid("682bfc31-dc6f-42db-ac47-233ab1aba084"),
                            StartTime = new DateTime(2025, 11, 24, 13, 27, 17, 176, DateTimeKind.Local).AddTicks(7022)
                        },
                        new
                        {
                            Id = new Guid("7799b9fa-cc36-4ce8-ac54-be35ae864392"),
                            BikeId = new Guid("2ff0d2de-a373-41ae-8018-f08f2590ec88"),
                            Duration = new TimeSpan(0, 5, 0, 0, 0),
                            RenterId = new Guid("cf7dcad8-2859-4f7e-95c1-c1471d134db0"),
                            StartTime = new DateTime(2025, 11, 24, 18, 27, 17, 176, DateTimeKind.Local).AddTicks(7023)
                        },
                        new
                        {
                            Id = new Guid("13a97ac3-4746-43bc-b4b7-d4cba1edd39b"),
                            BikeId = new Guid("3c43bc36-34e8-4fe3-ba3d-9b52777c6976"),
                            Duration = new TimeSpan(0, 6, 0, 0, 0),
                            RenterId = new Guid("3ac86426-26df-46cb-b4f2-576f442d104e"),
                            StartTime = new DateTime(2025, 11, 24, 20, 27, 17, 176, DateTimeKind.Local).AddTicks(7025)
                        },
                        new
                        {
                            Id = new Guid("d389a5a6-d398-46f2-a5c3-730f75d41553"),
                            BikeId = new Guid("e2330abb-386b-45fe-8c3b-52ec852dee1f"),
                            Duration = new TimeSpan(0, 2, 30, 0, 0),
                            RenterId = new Guid("1c9e5593-74e4-4f32-bb1a-aa65013e9749"),
                            StartTime = new DateTime(2025, 11, 24, 21, 27, 17, 176, DateTimeKind.Local).AddTicks(7027)
                        },
                        new
                        {
                            Id = new Guid("7d833f9a-1bf3-4191-950b-d724fc3af9a1"),
                            BikeId = new Guid("61865875-b804-4baa-8b2a-3260e62b84f3"),
                            Duration = new TimeSpan(0, 3, 30, 0, 0),
                            RenterId = new Guid("9d22c91c-85c9-44ac-85d6-2d0cf9c0513c"),
                            StartTime = new DateTime(2025, 11, 24, 22, 27, 17, 176, DateTimeKind.Local).AddTicks(7028)
                        },
                        new
                        {
                            Id = new Guid("6957a893-bdee-4e3d-9c19-22bbd4b04710"),
                            BikeId = new Guid("80d70b89-4692-4eda-9492-cf898aac545d"),
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            RenterId = new Guid("9cec14bf-3470-4394-9899-fdf3519f699f"),
                            StartTime = new DateTime(2025, 11, 23, 22, 27, 17, 176, DateTimeKind.Local).AddTicks(7031)
                        },
                        new
                        {
                            Id = new Guid("d44dc785-ed28-4259-8c64-0de1f1768277"),
                            BikeId = new Guid("3c43bc36-34e8-4fe3-ba3d-9b52777c6976"),
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            RenterId = new Guid("590c9949-a9d3-4084-81b4-d2b5c59cc0e7"),
                            StartTime = new DateTime(2025, 11, 24, 8, 27, 17, 176, DateTimeKind.Local).AddTicks(7033)
                        },
                        new
                        {
                            Id = new Guid("62953104-b9e1-4021-88a2-63f7b78ed558"),
                            BikeId = new Guid("e2330abb-386b-45fe-8c3b-52ec852dee1f"),
                            Duration = new TimeSpan(0, 5, 0, 0, 0),
                            RenterId = new Guid("d8abaf64-e960-486d-a064-7134dc4c0522"),
                            StartTime = new DateTime(2025, 11, 24, 11, 27, 17, 176, DateTimeKind.Local).AddTicks(7034)
                        },
                        new
                        {
                            Id = new Guid("447a3edb-7bd9-4467-bdd4-b713d189d934"),
                            BikeId = new Guid("279902b6-a996-4fe1-8de8-0f36cfcff3eb"),
                            Duration = new TimeSpan(0, 4, 0, 0, 0),
                            RenterId = new Guid("cf7dcad8-2859-4f7e-95c1-c1471d134db0"),
                            StartTime = new DateTime(2025, 11, 24, 15, 27, 17, 176, DateTimeKind.Local).AddTicks(7036)
                        },
                        new
                        {
                            Id = new Guid("45467e33-19f4-4465-8dee-8e55be3c6a19"),
                            BikeId = new Guid("2ff0d2de-a373-41ae-8018-f08f2590ec88"),
                            Duration = new TimeSpan(0, 2, 30, 0, 0),
                            RenterId = new Guid("1c9e5593-74e4-4f32-bb1a-aa65013e9749"),
                            StartTime = new DateTime(2025, 11, 24, 17, 27, 17, 176, DateTimeKind.Local).AddTicks(7037)
                        },
                        new
                        {
                            Id = new Guid("afd870f1-6346-42fe-bc98-836f32e16849"),
                            BikeId = new Guid("9ca5637c-9c10-419e-9c35-db2d523f5b08"),
                            Duration = new TimeSpan(0, 3, 30, 0, 0),
                            RenterId = new Guid("9d22c91c-85c9-44ac-85d6-2d0cf9c0513c"),
                            StartTime = new DateTime(2025, 11, 24, 19, 27, 17, 176, DateTimeKind.Local).AddTicks(7039)
                        },
                        new
                        {
                            Id = new Guid("46de07ab-24f5-497d-9d1f-78512c0ab9f6"),
                            BikeId = new Guid("36358c4c-8620-4fb5-9502-e1ea23d0d3e1"),
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            RenterId = new Guid("9cec14bf-3470-4394-9899-fdf3519f699f"),
                            StartTime = new DateTime(2025, 11, 24, 21, 57, 17, 176, DateTimeKind.Local).AddTicks(7040)
                        },
                        new
                        {
                            Id = new Guid("06ba3375-11d9-49b3-9db5-73703c4b24b0"),
                            BikeId = new Guid("e2330abb-386b-45fe-8c3b-52ec852dee1f"),
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            RenterId = new Guid("9bf4355d-d000-4822-9bd1-dea296610a3a"),
                            StartTime = new DateTime(2025, 11, 24, 22, 57, 17, 176, DateTimeKind.Local).AddTicks(7042)
                        },
                        new
                        {
                            Id = new Guid("b7cd534b-1b61-4e3c-b6a2-74e0c79a86c7"),
                            BikeId = new Guid("2ff0d2de-a373-41ae-8018-f08f2590ec88"),
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            RenterId = new Guid("682bfc31-dc6f-42db-ac47-233ab1aba084"),
                            StartTime = new DateTime(2025, 11, 24, 23, 15, 17, 176, DateTimeKind.Local).AddTicks(7044)
                        });
                });

            modelBuilder.Entity("BikeRentalPoint.Domain.Models.Renter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.ToTable("renter", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9cec14bf-3470-4394-9899-fdf3519f699f"),
                            LastName = "Иванов",
                            MiddleName = "Иванович",
                            Name = "Иван",
                            PhoneNumber = "111-111"
                        },
                        new
                        {
                            Id = new Guid("590c9949-a9d3-4084-81b4-d2b5c59cc0e7"),
                            LastName = "Петров",
                            MiddleName = "Петрович",
                            Name = "Петр",
                            PhoneNumber = "222-222"
                        },
                        new
                        {
                            Id = new Guid("9bf4355d-d000-4822-9bd1-dea296610a3a"),
                            LastName = "Сидоров",
                            MiddleName = "Сидорович",
                            Name = "Сидор",
                            PhoneNumber = "333-333"
                        },
                        new
                        {
                            Id = new Guid("d8abaf64-e960-486d-a064-7134dc4c0522"),
                            LastName = "Алексеев",
                            MiddleName = "Николаевич",
                            Name = "Алексей",
                            PhoneNumber = "444-444"
                        },
                        new
                        {
                            Id = new Guid("682bfc31-dc6f-42db-ac47-233ab1aba084"),
                            LastName = "Васильев",
                            MiddleName = "Павлович",
                            Name = "Василий",
                            PhoneNumber = "555-555"
                        },
                        new
                        {
                            Id = new Guid("cf7dcad8-2859-4f7e-95c1-c1471d134db0"),
                            LastName = "Кузнецов",
                            MiddleName = "Игоревич",
                            Name = "Сергей",
                            PhoneNumber = "666-666"
                        },
                        new
                        {
                            Id = new Guid("3ac86426-26df-46cb-b4f2-576f442d104e"),
                            LastName = "Никитин",
                            MiddleName = "Андреевич",
                            Name = "Никита",
                            PhoneNumber = "777-777"
                        },
                        new
                        {
                            Id = new Guid("1c9e5593-74e4-4f32-bb1a-aa65013e9749"),
                            LastName = "Федоров",
                            MiddleName = "Владимирович",
                            Name = "Федор",
                            PhoneNumber = "888-888"
                        },
                        new
                        {
                            Id = new Guid("9d22c91c-85c9-44ac-85d6-2d0cf9c0513c"),
                            LastName = "Смирнов",
                            MiddleName = "Валерьевич",
                            Name = "Семен",
                            PhoneNumber = "999-999"
                        },
                        new
                        {
                            Id = new Guid("b7491013-1f84-4866-a8e7-730c226c3659"),
                            LastName = "Попов",
                            MiddleName = "Алексеевич",
                            Name = "Дмитрий",
                            PhoneNumber = "000-000"
                        });
                });

            modelBuilder.Entity("BikeRentalPoint.Domain.Models.Bike", b =>
                {
                    b.HasOne("BikeRentalPoint.Domain.Models.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("BikeRentalPoint.Domain.Models.Rent", b =>
                {
                    b.HasOne("BikeRentalPoint.Domain.Models.Bike", "Bike")
                        .WithMany()
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeRentalPoint.Domain.Models.Renter", "Renter")
                        .WithMany()
                        .HasForeignKey("RenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bike");

                    b.Navigation("Renter");
                });
#pragma warning restore 612, 618
        }
    }
}
