// <auto-generated />
using System;
using BikeRentalPoint.Infrastructure.EfCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BikeRentalPoint.Infrastructure.EfCore.Migrations
{
    [DbContext(typeof(BikeRentalPointDbContext))]
    partial class BikeRentalPointDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BikeRentalPoint.Domain.Models.Bike", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("color");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("char(36)")
                        .HasColumnName("model_id");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("serial_number");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.ToTable("bike", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111124"),
                            Color = "Red",
                            ModelId = new Guid("11111111-1111-1111-1111-111111111110"),
                            SerialNumber = "101"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111125"),
                            Color = "Blue",
                            ModelId = new Guid("11111111-1111-1111-1111-111111111111"),
                            SerialNumber = "102"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111126"),
                            Color = "Black",
                            ModelId = new Guid("11111111-1111-1111-1111-111111111112"),
                            SerialNumber = "103"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111127"),
                            Color = "Green",
                            ModelId = new Guid("11111111-1111-1111-1111-111111111113"),
                            SerialNumber = "104"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111128"),
                            Color = "White",
                            ModelId = new Guid("11111111-1111-1111-1111-111111111114"),
                            SerialNumber = "105"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111129"),
                            Color = "Yellow",
                            ModelId = new Guid("11111111-1111-1111-1111-111111111115"),
                            SerialNumber = "106"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111112a"),
                            Color = "Silver",
                            ModelId = new Guid("11111111-1111-1111-1111-111111111116"),
                            SerialNumber = "107"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111112b"),
                            Color = "Gray",
                            ModelId = new Guid("11111111-1111-1111-1111-111111111117"),
                            SerialNumber = "108"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111112c"),
                            Color = "Orange",
                            ModelId = new Guid("11111111-1111-1111-1111-111111111118"),
                            SerialNumber = "109"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111112d"),
                            Color = "Purple",
                            ModelId = new Guid("11111111-1111-1111-1111-111111111119"),
                            SerialNumber = "110"
                        });
                });

            modelBuilder.Entity("BikeRentalPoint.Domain.Models.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("BikeType")
                        .HasColumnType("int")
                        .HasColumnName("bike_type");

                    b.Property<double?>("BikeWeight")
                        .HasColumnType("double")
                        .HasColumnName("bike_weight");

                    b.Property<int>("BrakeType")
                        .HasColumnType("int")
                        .HasColumnName("brake_type");

                    b.Property<double?>("MaxPassengerWeight")
                        .HasColumnType("double")
                        .HasColumnName("max_passenger_weight");

                    b.Property<int?>("ModelYear")
                        .HasColumnType("int")
                        .HasColumnName("model_year");

                    b.Property<decimal>("PricePerHour")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price_per_hour");

                    b.Property<double?>("WheelSize")
                        .HasColumnType("double")
                        .HasColumnName("wheel_size");

                    b.HasKey("Id");

                    b.ToTable("model", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111110"),
                            BikeType = 0,
                            BikeWeight = 9.0,
                            BrakeType = 1,
                            MaxPassengerWeight = 100.0,
                            ModelYear = 2022,
                            PricePerHour = 12m,
                            WheelSize = 28.0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BikeType = 1,
                            BikeWeight = 11.0,
                            BrakeType = 0,
                            MaxPassengerWeight = 110.0,
                            ModelYear = 2021,
                            PricePerHour = 10m,
                            WheelSize = 26.0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111112"),
                            BikeType = 1,
                            BikeWeight = 13.0,
                            BrakeType = 1,
                            MaxPassengerWeight = 120.0,
                            ModelYear = 2023,
                            PricePerHour = 15m,
                            WheelSize = 29.0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111113"),
                            BikeType = 2,
                            BikeWeight = 10.0,
                            BrakeType = 0,
                            MaxPassengerWeight = 90.0,
                            ModelYear = 2020,
                            PricePerHour = 9m,
                            WheelSize = 27.5
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111114"),
                            BikeType = 0,
                            BikeWeight = 12.0,
                            BrakeType = 2,
                            MaxPassengerWeight = 100.0,
                            ModelYear = 2024,
                            PricePerHour = 14m,
                            WheelSize = 28.0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111115"),
                            BikeType = 4,
                            BikeWeight = 8.0,
                            BrakeType = 3,
                            MaxPassengerWeight = 80.0,
                            ModelYear = 2019,
                            PricePerHour = 8m,
                            WheelSize = 24.0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111116"),
                            BikeType = 3,
                            BikeWeight = 14.0,
                            BrakeType = 1,
                            MaxPassengerWeight = 100.0,
                            ModelYear = 2024,
                            PricePerHour = 16m,
                            WheelSize = 26.0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111117"),
                            BikeType = 1,
                            BikeWeight = 15.0,
                            BrakeType = 5,
                            MaxPassengerWeight = 130.0,
                            ModelYear = 2023,
                            PricePerHour = 13m,
                            WheelSize = 29.0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111118"),
                            BikeType = 2,
                            BikeWeight = 11.0,
                            BrakeType = 0,
                            MaxPassengerWeight = 95.0,
                            ModelYear = 2021,
                            PricePerHour = 11m,
                            WheelSize = 27.0
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111119"),
                            BikeType = 0,
                            BikeWeight = 12.0,
                            BrakeType = 1,
                            MaxPassengerWeight = 120.0,
                            ModelYear = 2025,
                            PricePerHour = 17m,
                            WheelSize = 28.0
                        });
                });

            modelBuilder.Entity("BikeRentalPoint.Domain.Models.Rent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<Guid>("BikeId")
                        .HasColumnType("char(36)")
                        .HasColumnName("bike_id");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time(6)")
                        .HasColumnName("duration");

                    b.Property<Guid>("RenterId")
                        .HasColumnType("char(36)")
                        .HasColumnName("renter_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("BikeId");

                    b.HasIndex("RenterId");

                    b.ToTable("rent", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111112e"),
                            BikeId = new Guid("11111111-1111-1111-1111-111111111124"),
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            RenterId = new Guid("11111111-1111-1111-1111-11111111111a"),
                            StartTime = new DateTime(2025, 12, 14, 19, 11, 17, 17, DateTimeKind.Local).AddTicks(1164)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111112f"),
                            BikeId = new Guid("11111111-1111-1111-1111-111111111125"),
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            RenterId = new Guid("11111111-1111-1111-1111-11111111111b"),
                            StartTime = new DateTime(2025, 12, 15, 5, 11, 17, 17, DateTimeKind.Local).AddTicks(1756)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111130"),
                            BikeId = new Guid("11111111-1111-1111-1111-111111111126"),
                            Duration = new TimeSpan(0, 4, 0, 0, 0),
                            RenterId = new Guid("11111111-1111-1111-1111-11111111111c"),
                            StartTime = new DateTime(2025, 12, 15, 15, 11, 17, 17, DateTimeKind.Local).AddTicks(1762)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111131"),
                            BikeId = new Guid("11111111-1111-1111-1111-111111111127"),
                            Duration = new TimeSpan(0, 1, 30, 0, 0),
                            RenterId = new Guid("11111111-1111-1111-1111-11111111111d"),
                            StartTime = new DateTime(2025, 12, 16, 1, 11, 17, 17, DateTimeKind.Local).AddTicks(1764)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111132"),
                            BikeId = new Guid("11111111-1111-1111-1111-111111111128"),
                            Duration = new TimeSpan(0, 2, 30, 0, 0),
                            RenterId = new Guid("11111111-1111-1111-1111-11111111111e"),
                            StartTime = new DateTime(2025, 12, 16, 11, 11, 17, 17, DateTimeKind.Local).AddTicks(1766)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111133"),
                            BikeId = new Guid("11111111-1111-1111-1111-111111111129"),
                            Duration = new TimeSpan(0, 5, 0, 0, 0),
                            RenterId = new Guid("11111111-1111-1111-1111-11111111111f"),
                            StartTime = new DateTime(2025, 12, 16, 16, 11, 17, 17, DateTimeKind.Local).AddTicks(1768)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111134"),
                            BikeId = new Guid("11111111-1111-1111-1111-11111111112a"),
                            Duration = new TimeSpan(0, 6, 0, 0, 0),
                            RenterId = new Guid("11111111-1111-1111-1111-111111111120"),
                            StartTime = new DateTime(2025, 12, 16, 18, 11, 17, 17, DateTimeKind.Local).AddTicks(1770)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111135"),
                            BikeId = new Guid("11111111-1111-1111-1111-11111111112b"),
                            Duration = new TimeSpan(0, 2, 30, 0, 0),
                            RenterId = new Guid("11111111-1111-1111-1111-111111111121"),
                            StartTime = new DateTime(2025, 12, 16, 19, 11, 17, 17, DateTimeKind.Local).AddTicks(1772)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111136"),
                            BikeId = new Guid("11111111-1111-1111-1111-11111111112c"),
                            Duration = new TimeSpan(0, 3, 30, 0, 0),
                            RenterId = new Guid("11111111-1111-1111-1111-111111111122"),
                            StartTime = new DateTime(2025, 12, 16, 20, 11, 17, 17, DateTimeKind.Local).AddTicks(1784)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111137"),
                            BikeId = new Guid("11111111-1111-1111-1111-111111111126"),
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            RenterId = new Guid("11111111-1111-1111-1111-11111111111a"),
                            StartTime = new DateTime(2025, 12, 15, 20, 11, 17, 17, DateTimeKind.Local).AddTicks(1787)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111138"),
                            BikeId = new Guid("11111111-1111-1111-1111-11111111112a"),
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            RenterId = new Guid("11111111-1111-1111-1111-11111111111b"),
                            StartTime = new DateTime(2025, 12, 16, 6, 11, 17, 17, DateTimeKind.Local).AddTicks(1789)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111139"),
                            BikeId = new Guid("11111111-1111-1111-1111-11111111112b"),
                            Duration = new TimeSpan(0, 5, 0, 0, 0),
                            RenterId = new Guid("11111111-1111-1111-1111-11111111111d"),
                            StartTime = new DateTime(2025, 12, 16, 9, 11, 17, 17, DateTimeKind.Local).AddTicks(1791)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111113a"),
                            BikeId = new Guid("11111111-1111-1111-1111-111111111128"),
                            Duration = new TimeSpan(0, 4, 0, 0, 0),
                            RenterId = new Guid("11111111-1111-1111-1111-11111111111f"),
                            StartTime = new DateTime(2025, 12, 16, 13, 11, 17, 17, DateTimeKind.Local).AddTicks(1792)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111113b"),
                            BikeId = new Guid("11111111-1111-1111-1111-111111111129"),
                            Duration = new TimeSpan(0, 2, 30, 0, 0),
                            RenterId = new Guid("11111111-1111-1111-1111-111111111121"),
                            StartTime = new DateTime(2025, 12, 16, 15, 11, 17, 17, DateTimeKind.Local).AddTicks(1822)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111113c"),
                            BikeId = new Guid("11111111-1111-1111-1111-111111111127"),
                            Duration = new TimeSpan(0, 3, 30, 0, 0),
                            RenterId = new Guid("11111111-1111-1111-1111-111111111122"),
                            StartTime = new DateTime(2025, 12, 16, 17, 11, 17, 17, DateTimeKind.Local).AddTicks(1825)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111113d"),
                            BikeId = new Guid("11111111-1111-1111-1111-11111111112d"),
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            RenterId = new Guid("11111111-1111-1111-1111-11111111111a"),
                            StartTime = new DateTime(2025, 12, 16, 19, 41, 17, 17, DateTimeKind.Local).AddTicks(1827)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111113e"),
                            BikeId = new Guid("11111111-1111-1111-1111-11111111112b"),
                            Duration = new TimeSpan(0, 3, 0, 0, 0),
                            RenterId = new Guid("11111111-1111-1111-1111-11111111111c"),
                            StartTime = new DateTime(2025, 12, 16, 20, 41, 17, 17, DateTimeKind.Local).AddTicks(1830)
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111113f"),
                            BikeId = new Guid("11111111-1111-1111-1111-111111111129"),
                            Duration = new TimeSpan(0, 2, 0, 0, 0),
                            RenterId = new Guid("11111111-1111-1111-1111-11111111111e"),
                            StartTime = new DateTime(2025, 12, 16, 20, 59, 17, 17, DateTimeKind.Local).AddTicks(1832)
                        });
                });

            modelBuilder.Entity("BikeRentalPoint.Domain.Models.Renter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.ToTable("renter", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111111a"),
                            LastName = "Иванов",
                            MiddleName = "Иванович",
                            Name = "Иван",
                            PhoneNumber = "111-111"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111111b"),
                            LastName = "Петров",
                            MiddleName = "Петрович",
                            Name = "Петр",
                            PhoneNumber = "222-222"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111111c"),
                            LastName = "Сидоров",
                            MiddleName = "Сидорович",
                            Name = "Сидор",
                            PhoneNumber = "333-333"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111111d"),
                            LastName = "Алексеев",
                            MiddleName = "Николаевич",
                            Name = "Алексей",
                            PhoneNumber = "444-444"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111111e"),
                            LastName = "Васильев",
                            MiddleName = "Павлович",
                            Name = "Василий",
                            PhoneNumber = "555-555"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-11111111111f"),
                            LastName = "Кузнецов",
                            MiddleName = "Игоревич",
                            Name = "Сергей",
                            PhoneNumber = "666-666"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111120"),
                            LastName = "Никитин",
                            MiddleName = "Андреевич",
                            Name = "Никита",
                            PhoneNumber = "777-777"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111121"),
                            LastName = "Федоров",
                            MiddleName = "Владимирович",
                            Name = "Федор",
                            PhoneNumber = "888-888"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111122"),
                            LastName = "Смирнов",
                            MiddleName = "Валерьевич",
                            Name = "Семен",
                            PhoneNumber = "999-999"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111123"),
                            LastName = "Попов",
                            MiddleName = "Алексеевич",
                            Name = "Дмитрий",
                            PhoneNumber = "000-000"
                        });
                });

            modelBuilder.Entity("BikeRentalPoint.Domain.Models.Bike", b =>
                {
                    b.HasOne("BikeRentalPoint.Domain.Models.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Model");
                });

            modelBuilder.Entity("BikeRentalPoint.Domain.Models.Rent", b =>
                {
                    b.HasOne("BikeRentalPoint.Domain.Models.Bike", "Bike")
                        .WithMany()
                        .HasForeignKey("BikeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BikeRentalPoint.Domain.Models.Renter", "Renter")
                        .WithMany()
                        .HasForeignKey("RenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bike");

                    b.Navigation("Renter");
                });
#pragma warning restore 612, 618
        }
    }
}
